// <auto-generated />
namespace CMS_Golbarg.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AfterChangePayCoin_PayIdToNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AfterChangePayCoin_PayIdToNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201707021617593_AfterChangePayCoin_PayIdToNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
